permalink   : /:categories/:year/:title/
markdown    : kramdown
highlighter : rouge
gems:
  - jekyll-paginate
  - jekyll-seo-tag

paginate: 2 #6
comments: true
paginate_path: "/page/:num"

sass:
  sass_dir: _scss
  style: compressed

# Site settings
title: Reformed at Wheaton
description: "The thoughts of a Reformed, Wheaton College student."
email: jacob.rhoda@my.wheaton.edu
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://reformedatwheaton.jadar.net"
disqus_shortname: "jadar"
google_analytics: UA-48951211-2

# social footer
social:
  github:
    slug: github
    link: http://github.com/jadar
  linkedin:
    slug: linkedin
    link: http://linkedin.com/in/jacob-r-44a599122
