permalink   : /:categories/:year/:title/
markdown    : kramdown
highlighter : pygments
gems: [jekyll-paginate]

paginate: 2 #6
comments: true
paginate_path: "/page/:num"

# source: source
# destination: www
sass:
  sass_dir: _scss
  style: compressed

# Site settings
title: Reformed at Wheaton
description: "The thoughts of a Reformed, Wheaton College student."
email: jacob.rhoda@my.wheaton.edu
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://reformedatwheaton.jadar.net"
disqus_shortname: "jadar"
# google_analytics: UA-52446115-1

# social footer
social:
  github:
    slug: github
    link: http://github.com/jadar
  facebook:
    slug: facebook
    link: http://facebook.com/jacob.rhoda1
  twitter:
    slug: twitter
    link: http://twitter.com/jadardev
  instagram:
    slug: instagram
    link: http://instagram.com/jadardev
  linkedin:
    slug: linkedin
    link: http://linkedin.com/in/jacob-r-44a599122
